CREATE TABLE IF NOT EXISTS pro_payment_orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL, code VARCHAR(40) NOT NULL UNIQUE,
    amount INT UNSIGNED NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL, paid_at DATETIME NULL,
    INDEX(user_id, status)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS pro_payment_transactions (
    transaction_id VARCHAR(64) PRIMARY KEY, order_id BIGINT UNSIGNED NULL,
    amount BIGINT UNSIGNED NOT NULL, reference_code VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
