
import React, { useMemo } from 'react';
import DOMPurify from 'dompurify';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import { unwrapImmini, stripComments, findClosingBrace } from '../utils/fileUtils';
import { stripExTestSolution, stripExTestChoices } from '../utils/latexParser';
import { TikZRenderer } from './TikZRenderer';
import { KATEX_MACROS, prepareLatexForRendering, splitLatexSegments } from '../utils/mathLatex';

interface MathRendererProps {
  content: string;
  className?: string;
  mode?: 'question' | 'solution' | 'all';
  renderChoices?: boolean;
  hideToolbar?: boolean;
  isExTest?: boolean;
  disableTikZ?: boolean;
}

// Smart split function to handle LaTeX delimiters and environments
const smartSplit = (str: string, delimiter: string): string[] => {
    const result: string[] = [];
    let current = '';
    let depth = 0; // tracking nested braces {}
    let inMath = false; // tracking $...$ or $$...$$
    let mathChar = ''; // '$' or '$$'
    let inEnv = 0; // tracking \begin{...} \end{...}

    for (let i = 0; i < str.length; i++) {
        const char = str[i];
        const nextChar = str[i + 1];

        // Handle math mode $ or $$
        if (char === '$' && str[i - 1] !== '\\') {
            if (nextChar === '$') {
                if (inMath && mathChar === '$$') {
                    inMath = false;
                    mathChar = '';
                } else if (!inMath) {
                    inMath = true;
                    mathChar = '$$';
                }
                current += '$$';
                i++;
                continue;
            } else {
                if (inMath && mathChar === '$') {
                    inMath = false;
                    mathChar = '';
                } else if (!inMath) {
                    inMath = true;
                    mathChar = '$';
                }
            }
        }

        // Handle braces
        if (char === '{' && str[i - 1] !== '\\') depth++;
        if (char === '}' && str[i - 1] !== '\\') depth--;

        // Handle environments \begin{...} \end{...}
        if (str.substring(i, i + 7) === '\\begin{') inEnv++;
        if (str.substring(i, i + 5) === '\\end{') inEnv--;

        // Split if delimiter found and we are not in any special mode
        if (char === delimiter && depth === 0 && !inMath && inEnv === 0) {
            result.push(current);
            current = '';
        } else {
            current += char;
        }
    }
    result.push(current);
    return result;
};

// Pre-process lists (enumerate/itemize) to HTML tags for better layout
const formatLatexLists = (text: string): string => {
    let res = text;
    
    // Clean environment wrappers nicely
    res = res.replace(/\\begin\s*\{center\}/gi, '').replace(/\\end\s*\{center\}/gi, '');
    
    // Better list handling that handles nesting by using simple string replacement 
    // and then cleaning up the </li> structure
    
    // 1. Process starts of lists
    res = res.replace(/\\begin\s*\{enumerate\}(?:\[.*?\])?/gi, '<ol class="list-decimal pl-6 space-y-2 my-2">');
    res = res.replace(/\\begin\s*\{(?:itemize|itemchoice)\}(?:\[.*?\])?/gi, '<ul class="list-disc pl-6 space-y-2 my-2">');
    
    // 2. Process ends of lists
    res = res.replace(/\\end\s*\{enumerate\}/gi, '</li></ol>');
    res = res.replace(/\\end\s*\{(?:itemize|itemchoice)\}/gi, '</li></ul>');
    
    // 3. Process items
    // Using a class for <li> to match Tailwind styling
    res = res.replace(/\\item/gi, '</li><li class="mt-1">');
    
    // 4. Cleanup: Remove the first </li> that's generated by the first \item
    // Any <ol...> or <ul...> that is immediately followed by a </li> should have that </li> removed correctly.
    // Also handle possible spaces between them.
    res = res.replace(/(<(ol|ul)[^>]*>)\s*<\/li>/gi, '$1');
    
    // 5. Cleanup: If there's a trailing \item just before \end, it might leave an empty <li></li>
    res = res.replace(/<li[^>]*>\s*<\/(ol|ul)>/gi, '</$1>');

    return res;
};

// Pre-process tables (longtable/tabular) to HTML tags
const formatLatexTables = (text: string): string => {
    return text;
};

// Component to render LaTeX tables natively
const LatexTable = ({ latex }: { latex: string }) => {
    const contentMatch = latex.match(/\\begin\s*\{(tabular|longtable|tabular\*)\}\s*(?:\[[^\]]*\])?\s*(?:\{[^{}]*?(?:\{[^{}]*?\}[^{}]*?)*\})?\s*(?:\{[^{}]*?(?:\{[^{}]*?\}[^{}]*?)*\})?([\s\S]*?)\\end\s*\{\1\}/i);
    if (!contentMatch) return <span>{latex}</span>;
    const tableContent = contentMatch[2];
    
    let tempContent = "";
    let depth = 0;
    let inEnv = 0;
    let inMath = false;
    for (let j = 0; j < tableContent.length; j++) {
        const char = tableContent[j];
        if (char === '{' && tableContent[j-1] !== '\\\\') depth++;
        if (char === '}' && tableContent[j-1] !== '\\\\') depth--;
        if (tableContent.substring(j, j+7) === '\\begin{') inEnv++;
        if (tableContent.substring(j, j+5) === '\\end{') inEnv--;
        if (char === '$' && tableContent[j-1] !== '\\\\') {
            if (tableContent[j+1] === '$') { inMath = !inMath; j++; }
            else inMath = !inMath;
        }
        if (tableContent.substring(j, j+2) === '\\\\' && depth === 0 && inEnv === 0 && !inMath) {
            tempContent += '||ROW_SEP||';
            j++;
        } else {
            tempContent += char;
        }
    }
    
    const rows = tempContent
        .replace(/\\(hline|toprule|midrule|bottomrule)/g, '')
        .split('||ROW_SEP||')
        .map(r => r.trim())
        .filter(r => r.length > 0 || r.includes('&'));

    return (
        <div className="overflow-x-auto my-6 p-1 max-w-full">
            <table className="mx-auto border-collapse border border-slate-300 bg-white text-sm shadow-md rounded-xl overflow-hidden">
                <tbody>
                    {rows.map((row, rIdx) => {
                        const cells = smartSplit(row, '&').map(c => c.trim());
                        return (
                            <tr key={rIdx} className="border-b border-slate-100 last:border-0 even:bg-slate-50/30">
                                {cells.map((cell, cIdx) => {
                                    const multiMatch = cell.match(/\\multicolumn\s*\{[^}]*\}\s*\{[^}]*\}\s*\{([\s\S]*)\}/);
                                    const cellContent = multiMatch ? multiMatch[1] : cell;
                                    const isLong = cellContent.length > 20 || cellContent.includes('\\\\');
                                    const tdClass = `border border-slate-300 p-3 text-center align-middle ${isLong ? '' : 'whitespace-nowrap'} min-w-[2rem]`;
                                    return (
                                        <td key={cIdx} className={tdClass}>
                                            {renderMathText(cellContent)}
                                        </td>
                                    );
                                })}
                            </tr>
                        );
                    })}
                </tbody>
            </table>
        </div>
    );
};

// Pre-process choices (\choice and \choiceTF) to HTML tags
const formatExTestChoices = (text: string): string => {
    let res = text;
    
    // Helper to extract choices using brace matching
    const extractChoices = (content: string, command: string) => {
        const results: string[] = [];
        const idx = content.indexOf(command);
        if (idx === -1) return null;
        
        let currentPos = idx + command.length;
        for (let i = 0; i < 4; i++) {
            const openBrace = content.indexOf('{', currentPos);
            if (openBrace === -1) break;
            
            // Check if there's only whitespace between
            const between = content.substring(currentPos, openBrace);
            if (!/^\s*$/.test(between) && i > 0) break;
            
            const closeBrace = findClosingBrace(content, openBrace);
            if (closeBrace === -1) break;
            
            results.push(content.substring(openBrace + 1, closeBrace));
            currentPos = closeBrace + 1;
        }
        
        if (results.length > 0) {
            return {
                fullMatch: content.substring(idx, currentPos),
                choices: results
            };
        }
        return null;
    };

    // Handle \choice
    let choiceData = extractChoices(res, '\\choice');
    while (choiceData) {
        const { fullMatch, choices } = choiceData;
        const htmlChoices = choices.map((content, idx) => {
            const label = String.fromCharCode(65 + idx); // A, B, C, D
            let cleanContent = content.replace(/\\True\s*/g, '').trim();
            
            // Capitalize first letter if it's an alphabetic character
            if (cleanContent.length > 0 && /^[a-zâêôưăđơàảãáạèẻẽéẹìỉĩíịòỏõóọùủũúụỳỷỹýỵ]/.test(cleanContent.toLowerCase())) {
                cleanContent = cleanContent.charAt(0).toUpperCase() + cleanContent.slice(1);
            }
            
            return `<div class="flex gap-2 items-baseline p-1 transition-all">
                <span class="font-bold text-indigo-600 shrink-0 w-6">${label}.</span>
                <span class="flex-1 min-w-0 leading-relaxed font-medium">${cleanContent}</span>
            </div>`;
        });
        
        const gridClass = choices.length <= 2 ? "grid-cols-1" : "grid-cols-1 md:grid-cols-2";
        const replacement = `<div class="grid ${gridClass} gap-x-6 gap-y-1 my-3 first:mt-0 last:mb-0">${htmlChoices.join('')}</div>`;
        res = res.split(fullMatch).join(replacement);
        choiceData = extractChoices(res, '\\choice');
    }

    // Handle \choiceTF
    let choiceTFData = extractChoices(res, '\\choiceTF');
    while (choiceTFData) {
        const { fullMatch, choices } = choiceTFData;
        const htmlChoices = choices.map((content, idx) => {
            let cleanContent = content.replace(/\\True\s*/g, '').trim();
            
            // Capitalize first letter
            if (cleanContent.length > 0 && /^[a-zâêôưăđơàảãáạèẻẽéẹìỉĩíịòỏõóọùủũúụỳỷỹýỵ]/.test(cleanContent.toLowerCase())) {
                cleanContent = cleanContent.charAt(0).toUpperCase() + cleanContent.slice(1);
            }
            
            return `<div class="flex gap-3 items-start border-b border-slate-100 last:border-0 py-3 px-2">
                <span class="font-black text-slate-300 shrink-0 w-8 text-sm">${String.fromCharCode(97 + idx)}.</span>
                <span class="flex-1 text-slate-700 font-medium">${cleanContent}</span>
            </div>`;
        });
        const replacement = `<div class="flex flex-col gap-0 my-4 p-4 bg-slate-50/50 rounded-2xl border border-slate-100 shadow-sm">${htmlChoices.join('')}</div>`;
        res = res.split(fullMatch).join(replacement);
        choiceTFData = extractChoices(res, '\\choiceTF');
    }

    // Handle \shortans for local rendering
    let shortansIdx = res.indexOf('\\shortans');
    while (shortansIdx !== -1) {
        const openBrace = res.indexOf('{', shortansIdx);
        if (openBrace !== -1) {
            const closeBrace = findClosingBrace(res, openBrace);
            if (closeBrace !== -1) {
                const answer = res.substring(openBrace + 1, closeBrace);
                // For local rendering, we show it as a highlighted answer box
                const replacement = `<span class="inline-flex items-center px-3 py-1 rounded-lg text-sm font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 mx-1 shadow-sm">${answer}</span>`;
                res = res.substring(0, shortansIdx) + replacement + res.substring(closeBrace + 1);
            } else break;
        } else break;
        shortansIdx = res.indexOf('\\shortans', shortansIdx + 1);
    }

    return res;
};

// Pre-process common LaTeX text formatting and sizing commands
const formatLatexTextCommands = (text: string): string => {
    let res = text;
    
    // Remove unwanted renewing commands like \renewcommand{\arraystretch}{1.4}
    res = res.replace(/\\renewcommand\s*\{[^{}]*\}\s*\{[^{}]*\}/g, '');
    
    // Headings
    res = res.replace(/\\section\*?\{([\s\S]*?)\}/g, '<h2 class="text-2xl font-bold text-slate-800 mt-6 mb-4">$1</h2>');
    res = res.replace(/\\subsection\*?\{([\s\S]*?)\}/g, '<h3 class="text-xl font-bold text-slate-700 mt-4 mb-3">$1</h3>');
    res = res.replace(/\\subsubsection\*?\{([\s\S]*?)\}/g, '<h4 class="text-lg font-bold text-slate-700 mt-3 mb-2">$1</h4>');
    
    // Spacing
    res = res.replace(/\\vspace\*?\{([\s\S]*?)\}/g, function(match, p1) {
        const val = p1.trim();
        // Translate LaTeX dimensions to basic CSS if possible
        if (/^[0-9.]+(cm|mm|in|pt|px|em|ex|rem)$/i.test(val)) {
            return `<div style="height: ${val}; width: 100%; display: block; clear: both;"></div>`;
        }
        return '<div class="h-4 w-full block clear-both"></div>'; 
    });
    
    res = res.replace(/\\hspace\*?\{([\s\S]*?)\}/g, function(match, p1) {
        const val = p1.trim();
        if (/^[0-9.]+(cm|mm|in|pt|px|em|ex|rem)$/i.test(val)) {
            return `<span style="width: ${val}; display: inline-block;"></span>`;
        }
        return '<span class="w-4 inline-block"></span>';
    });
    
    // Sizing and formatting commands to strip
    const stripCommands = ['Huge', 'huge', 'LARGE', 'Large', 'large', 'normalsize', 'small', 'footnotesize', 'scriptsize', 'tiny', 'bf', 'it', 'em', 'centering', 'raggedright', 'raggedleft'];
    stripCommands.forEach(cmd => {
        // Strip out {\Large ...}  or {\bf ...}
        const regexBrace = new RegExp(`\\{\\\\${cmd}\\s+([\\s\\S]*?)\\}`, 'g');
        res = res.replace(regexBrace, '$1');
        // Strip out \Large as a standalone command
        const regexStandalone = new RegExp(`\\\\${cmd}(\\s+|$|(?=[^a-zA-Z]))`, 'g');
        res = res.replace(regexStandalone, '');
    });

    // Formatting
    res = res.replace(/\\hfill\\?/g, '<span style="flex-grow: 1;"></span>');
    res = res.replace(/\\noindent\\?/g, '');
    res = res.replace(/\\centerline\{([\s\S]*?)\}/g, '<div class="text-center w-full">$1</div>');
    
    return res;
};

const wrapNakedMacros = (text: string): string => {
    let res = text;
    ['heva', 'hoac', 'vv', 'vec'].forEach(cmd => {
        let i = 0;
        const searchStr = `\\${cmd}{`;
        while ((i = res.indexOf(searchStr, i)) !== -1) {
            const openBrace = i + searchStr.length - 1;
            let depth = 1;
            let closeBrace = -1;
            for (let j = openBrace + 1; j < res.length; j++) {
                if (res[j] === '{') depth++;
                else if (res[j] === '}') depth--;
                if (depth === 0) {
                    closeBrace = j;
                    break;
                }
            }
            if (closeBrace !== -1) {
                const inner = res.substring(i, closeBrace + 1);
                const replacement = `\\(${inner}\\)`;
                res = res.substring(0, i) + replacement + res.substring(closeBrace + 1);
                i += replacement.length;
            } else {
                i++;
            }
        }
    });
    return res;
};

const renderMathText = (text: string) => {
    const s = prepareLatexForRendering(text)
        .replace(/\\textbf\{([\s\S]*?)\}/g, '<strong class="font-bold text-slate-900">$1</strong>')
        .replace(/\\textit\{([\s\S]*?)\}/g, '<em class="italic text-slate-700">$1</em>')
        .replace(/\\unit\{([\s\S]*?)\}/g, '\\text{$1}') // Handle \unit
        .replace(/\\unit\[([\s\S]*?)\]\{([\s\S]*?)\}/g, '$1\\text{ $2}'); // Handle \unit[val]{unit}

    // Split by math delimiters, being careful with escaped $
    // Using a more compatible regex (no negative lookbehind for older Safari)
    const parts = splitLatexSegments(s);

    return parts.map((part, i) => {
        if (!part) return null;
        
        // Check if it's a math block
        const isTable = /^\\begin\s*\{(tabular|longtable|tabular\*)\}/.test(part);
        if (isTable) {
            return <LatexTable key={i} latex={part} />;
        }
        
        const isDisplay = part.startsWith('$$') || part.startsWith('\\[') || part.startsWith('\\begin{align') || part.startsWith('\\begin{eqn') || part.startsWith('\\begin{case') || part.startsWith('\\begin{matrix') || part.startsWith('\\begin{pmatrix') || part.startsWith('\\begin{bmatrix') || part.startsWith('\\begin{Bmatrix') || part.startsWith('\\begin{vmatrix') || part.startsWith('\\begin{Vmatrix') || part.startsWith('\\begin{array');
        const isInline = part.startsWith('$') || part.startsWith('\\(');
        
        if (isDisplay || isInline) {
            let math = '';
            if (isDisplay) {
                if (part.startsWith('$$') || part.startsWith('\\[')) {
                    math = part.slice(2, -2);
                } else {
                    math = part; // Keep \begin{...} intact
                }
            } else {
                math = part.startsWith('\\(') ? part.slice(2, -2) : part.slice(1, -1);
            }
            
            try {
                const html = katex.renderToString(math, { 
                    displayMode: isDisplay, 
                    throwOnError: false, 
                    strict: false,
                    trust: false,
                    macros: KATEX_MACROS
                });
                return <span key={i} className="katex-wrapper" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(html) }} />;
            } catch { 
                return <span key={i} className="text-rose-500 font-mono text-[10px] bg-rose-50 px-1 rounded">{part}</span>; 
            }
        }
        
        // Text part
        let processedText = wrapNakedMacros(part);
        if (processedText !== part) {
            // If we wrapped naked macros, re-render this part to process the new math blocks
            return <React.Fragment key={i}>{renderMathText(processedText)}</React.Fragment>;
        }
        
        processedText = processedText
            .replace(/\\\\/g, '<br/>')
            .replace(/\\newline/g, '<br/>')
            .replace(/\\par/g, '<br/><br/>');

        return <span key={i} dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(processedText, { ALLOWED_TAGS: ['br', 'strong', 'em'], ALLOWED_ATTR: ['class'] }) }} />;
    });
};

export const MathRenderer: React.FC<MathRendererProps> = ({ 
    content, 
    className = '', 
    mode = 'all',
    renderChoices = true,
    hideToolbar = false,
    isExTest = false,
    disableTikZ = false
}) => {
    
    const { textPart, imageParts, solutionPart } = useMemo(() => {
        let cleanContent = stripComments(content || "");
        cleanContent = unwrapImmini(cleanContent);
        
        // Remove unwanted strings
        const unwantedRegex = /(?:\\textcolor\{red\}\{)?\s*Câu (?:dưới\s+)?(?:đây|này) dùng môi trường \{?chc\}? mới đúng\.?!\s*;?\s*\}?|Câu \d+[\.:\s]*/gi;
        cleanContent = cleanContent.replace(unwantedRegex, "").trim();
        
        let localContent = cleanContent;
        let extractedSolution = "";

        if (mode === 'all' || mode === 'solution') {
            const loigiaiIdx = localContent.indexOf('\\loigiai');
            if (loigiaiIdx !== -1) {
                const openBrace = localContent.indexOf('{', loigiaiIdx);
                if (openBrace !== -1) {
                    const closeBrace = findClosingBrace(localContent, openBrace);
                    if (closeBrace !== -1) {
                        extractedSolution = localContent.substring(openBrace + 1, closeBrace);
                        // Remove \loigiai{...} from main content
                        localContent = localContent.substring(0, loigiaiIdx) + localContent.substring(closeBrace + 1);
                        localContent = localContent.trim();
                    }
                }
            }
            

        }

        if (mode === 'solution') {
            localContent = extractedSolution || localContent;
        }

        // Standard processing
        if (mode === 'question') {
            localContent = stripExTestSolution(localContent);
            if (!renderChoices) localContent = stripExTestChoices(localContent);
            localContent = localContent.replace(/\\True/g, '');
        }

        localContent = localContent
            .replace(/\\begin\s*\{(ex|bt|vd|ex_test|loigiai|câu|vdu)\}(?:\[.*?\])?/gi, '')
            .replace(/\\end\s*\{(ex|bt|vd|ex_test|loigiai|câu|vdu)\}/gi, '')
            .trim();

        const tikzRegex = /(\\begin\s*\{\s*(tikzpicture|tkz-tab|tkz-euclide)\s*\}(?:\[[\s\S]*?\])?(?:\{[\s\S]*?\})?[\s\S]*?\\end\s*\{\s*(tikzpicture|tkz-tab|tkz-euclide)\s*\}|\[TIKZ_HASH:([a-f0-9]{64})\])/gi;
        const images: { code?: string, hash?: string }[] = [];
        const textOnly = localContent.replace(tikzRegex, (match, p1, p2, p3, hashMatch) => {
            if (disableTikZ) return match; // Keep the code in text if disabled
            if (hashMatch) images.push({ hash: hashMatch }); else images.push({ code: match });
            return ''; 
        });

        return {
            textPart: formatExTestChoices(formatLatexTables(formatLatexLists(formatLatexTextCommands(textOnly.trim())))),
            imageParts: images,
            solutionPart: mode === 'all' ? extractedSolution : ""
        };
    }, [content, mode, renderChoices, disableTikZ]);

    // --- RENDER ---
    
    // CASE 1: No Images -> Standard Render
    if (imageParts.length === 0) {
        return (
            <div className={`math-renderer flex flex-col gap-6 text-slate-800 leading-relaxed text-base md:text-lg ${className}`}>
                {mode === 'solution' && (
                    <div className="font-bold text-indigo-700 mb-2 py-2 border-b border-indigo-100 flex items-center gap-2">
                        <div className="w-1.5 h-6 bg-indigo-500 rounded-full"></div>
                        Hướng dẫn giải chi tiết:
                    </div>
                )}
                <div className="math-content inline-block w-full">
                    {renderMathText(isExTest ? formatExTestChoices(textPart) : textPart)}
                </div>
                {mode === 'all' && solutionPart && (
                    <div className="mt-8 p-6 bg-indigo-50/50 border border-indigo-100 rounded-2xl relative overflow-hidden group">
                        <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
                        <div className="font-bold text-indigo-700 mb-4 flex items-center gap-2 border-b border-indigo-100/50 pb-2">
                            <div className="w-1.5 h-6 bg-indigo-500 rounded-full"></div>
                            Lời giải chi tiết:
                        </div>
                        <div className="math-content">
                            <MathRenderer content={solutionPart} mode="question" renderChoices={false} isExTest={isExTest} hideToolbar={true} className="p-0 text-slate-700 italic" />
                        </div>
                    </div>
                )}
            </div>
        );
    }

    // CASE 2: Has Images -> Split Layout (Text Left | Images Right)
    return (
        <div className={`math-renderer flex flex-col md:flex-row gap-6 items-start ${className}`}>
            {/* Left Column: Text */}
            <div className="flex-1 flex flex-col gap-4 text-slate-800 leading-relaxed text-base md:text-lg min-w-0 w-full">
                {mode === 'solution' && (
                    <div className="font-bold text-indigo-700 mb-2 py-2 border-b border-indigo-100 flex items-center gap-2">
                        <div className="w-1.5 h-6 bg-indigo-500 rounded-full"></div>
                        Hướng dẫn giải chi tiết:
                    </div>
                )}
                <div className="math-content inline-block w-full">
                    {renderMathText(isExTest ? formatExTestChoices(textPart) : textPart)}
                </div>
                
                {mode === 'all' && solutionPart && (
                    <div className="mt-8 p-6 bg-indigo-50/50 border border-indigo-100 rounded-2xl relative overflow-hidden group">
                        <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
                        <div className="font-bold text-indigo-700 mb-4 flex items-center gap-2 border-b border-indigo-100/50 pb-2">
                            <div className="w-1.5 h-6 bg-indigo-500 rounded-full"></div>
                            Lời giải chi tiết:
                        </div>
                        <div className="math-content">
                            <MathRenderer content={solutionPart} mode="question" renderChoices={false} isExTest={isExTest} hideToolbar={true} className="p-0 text-slate-700 italic" />
                        </div>
                    </div>
                )}
            </div>

            {/* Right Column: Images Stack */}
            <div className="shrink-0 w-full md:w-[350px] flex flex-col items-stretch gap-4 border-l border-slate-100 pl-0 md:pl-6">
                {imageParts.map((img, idx) => {
                    const i = img as { code?: string, hash?: string };
                    return (
                        <div key={idx} className="w-full">
                            <TikZRenderer code={i.code} hash={i.hash} hideToolbar={hideToolbar || !!i.hash} mode={mode} />
                        </div>
                    );
                })}
            </div>
        </div>
    );
};
